USE LIBRARY;
SHOW DATABASES;
SHOW TABLES;

SELECT CONCAT (Author_fname," ",Autho_lname ) AS AUTHOR_NAME From BOOKS;

SELECT Author_fname,Autho_lname, CONCAT(Author_fname, " ", Autho_lname) AS FullNAME FROM BOOKS;

SELECT CONCAT_WS("_",Book_id, Author_fname,Autho_lnAme) AS AUTHORS FROM BOOKS;


--  SUBSTRING

SELECT SUBSTRING("HELLO WORLD ",2,5);
SELECT SUBSTRING("HELLO WORLD",5);
SELECT SUBSTRING("HELLO WORLD",-3);

SELECT SUBSTRING(Title,1,10) FROM BOOKS;

SELECT CONCAT(SUBSTRING(Title,1,10) ,"...")AS SHORTTITLE FROM BOOKS;

--  REPLACE

SELECT REPLACE("HELLO WORLD", "HELL", "****");
SELECT REPLACE ("HELLO WORLD", "L","7");

SELECT REPLACE(Title,"e",3) FROM BOOKS;
SELECT SUBSTRING(REPLACE(Title,"e",3),1,10) FROM BOOKS; 

--  REVERSE
SELECT REVERSE("HELLO WORLD");

SELECT REVERSE(Author_fname) FROM BOOKS;

--  CHARLENGTH
SELECT CHAR_LENGTH("HELLO WORLD");
SELECT Title,CHAR_LENGTH(Title) FROM BOOKS;
SELECT Author_fname, CHAR_LENGTH(Author_fname) FROM BOOKS;
SELECT CONCAT(Author_fname, " is ", CHAR_LENGTH(Author_fname)," char long") FROM BOOKS;

--  UPPER AND LOWER
SELECT UPPER("hello");
SELECT LOWER("HELLO");
SELECT UPPER(Author_fname) FROM BOOKS;
SELECT LOWER(Title) FROM BOOKS;

